export const READ_EXCHANGE_RATES_START = 'READ_EXCHANGE_RATES_START';
export const READ_EXCHANGE_RATES_END = 'READ_EXCHANGE_RATES_END';

export const EXCHANGE_START = 'EXCHANGE_START';
export const EXCHANGE_END = 'EXCHANGE_END';

export const READ_STATISTICS_START = 'READ_STATISTICS_START';
export const READ_STATISTICS_END = 'READ_STATISTICS_END';

export const READ_SETTINGS_START = 'READ_SETTINGS_START';
export const READ_SETTINGS_END = 'READ_SETTINGS_END';

export const UPDATE_SETTINGS_START = 'UPDATE_SETTINGS_END';
export const UPDATE_SETTINGS_END = 'UPDATE_SETTINGS_END';

export const OPERATION_TYPE = {
  BUY: 'buy',
  SELL: 'sell',
  EXCHANGE: 'exchange',
};

export const ALLOWED_OPERATIONS = Object.values(OPERATION_TYPE);
